Pixiv
Saebasol/Hiyobot_deprecated pull request #75
Opened 2021-01-16 06:33 UTC by ombe1229

2021-01-16 06:36 UTC, kijk2869 requested changes
May be mobile bug.

2021-01-16 06:36 UTC, kijk2869 commented on utils/pixiv.py
>          pixiv_latency1 = time.perf_counter()
Indent error

2021-01-16 06:36 UTC, kijk2869 commented on utils/pixiv.py
>      illust_url = await get_original_url(info.id)
Indent error

2021-01-16 06:36 UTC, kijk2869 approved these changes

2021-01-18 11:56 UTC, SaidBySolo approved these changes

2021-01-18 11:56 UTC, SaidBySolo commented
Merge into #76

2021-01-18 11:56 UTC, merged